# Assignment 25

Consider the below code to answer further questions:

```python
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
```

1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Ans: Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list object, while the variable array_list is a NumPy ndarray object.

In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object=list_)

print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))

Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3. Considering the following changes in the variable, array_list:

    array_list = np.array(object = list_, dtype = int)
    
    Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Ans: Yes, there will be a difference in the data type of the elements present in list_ and array_list if we specify dtype=int when creating array_list. This is because we are explicitly telling NumPy to convert the elements in list_ to integers, rather than letting NumPy determine the data type automatically.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(int(element)))

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


4. Write a code to find the following characteristics of variable, num_array:
      1. shape
      2. size

In [4]:
import numpy as np

# create a sample 2D ndarray with shape (3, 4)
num_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# print the shape and size of the ndarray
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (3, 4)
Size of num_array: 12


5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

    [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [5]:
import numpy as np

# create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

# print the array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


6. Create an identity matrix of shape (5,5) using numpy functions?

    [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [6]:
import numpy as np

# create a 5x5 identity matrix
identity_matrix = np.identity(5)

# print the matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
!git add .

The file will have its original line endings in your working directory
The file will have its original line endings in your working directory


fatal: unable to access 'https://github.com/tusharjain8177/Data_science_masters_assignments-.git/': Failed to connect to github.com port 443 after 21140 ms: Timed out
